services:

  db:
    image: mysql:5.7
    restart: always
    container_name: mysql
    volumes:
      - ${HOME_PATH}${APP_PATH}/mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - jellyfin_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    container_name: phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT}:80"
    environment:
      PMA_HOST: db
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - jellyfin_net

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    build:
      context: ${HOME_PATH}${APP_PATH}/nginx_data
      dockerfile: Dockerfile
    restart: always
    ports:
      - '${NGINX_HTTP}:80' # Public HTTP Port
      - '${NGINX_HTTPS}:443' # Public HTTPS Port
      - '${NGINX_WEB}:81' # Admin Web Port
    environment:
      DB_MYSQL_HOST: ${MYSQL_HOST}
      DB_MYSQL_PORT: ${MYSQL_PORT}
      DB_MYSQL_USER: "root"
      DB_MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_MYSQL_NAME: ${MYSQL_DATABASE}
    volumes:
      - ${HOME_PATH}${APP_PATH}/nginx_data/config/wg0.conf:/etc/wireguard/wg0.conf
      - ${HOME_PATH}${APP_PATH}/nginx_data/data:/data
      - ${HOME_PATH}${APP_PATH}/nginx_data/letsencrypt:/etc/letsencrypt
      - ${HOME_PATH}${APP_PATH}/nginx_data/data/html:/usr/share/nginx/html
    privileged: true
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    networks:
      - jellyfin_net

  wetty:
    image: wettyoss/wetty
    container_name: wetty
    ports:
      - "${WETTY_PORT}:3000"
    volumes:
      - ${HOME_PATH}/.ssh:/root/.ssh:ro
    command: ["node", ".", "--command", "ssh -t ${WETTY_SSH_COMMAND}", "--base", "/"]
    restart: "always"
    networks:
      - jellyfin_net

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    ports:
      - ${JELLYFIN_PORT}:8096
    volumes:
      - ${HOME_PATH}${APP_PATH}/jellyfin/config:/config
      - ${HOME_PATH}${APP_PATH}/jellyfin/cache:/cache
      - ${STORAGE_PATH}/jellyfin/media:/media
    restart: 'always'
    networks:
      - jellyfin_net

  wg-easy:
    environment:
      - LANG=it
      - WG_HOST=${WG_HOST}

      - PASSWORD_HASH=${WG_PASSWORD_HASH}

    image: ghcr.io/wg-easy/wg-easy
    container_name: wg-easy
    volumes:
      - ${HOME_PATH}${APP_PATH}/wireguard:/etc/wireguard
    ports:
      - "${WG_PORT_UDP}:51820/udp"
      - "${WG_PORT_TCP}:51821/tcp"
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    networks:
      - jellyfin_net
  
  streaming-community-api:
    build:
      context: ${HOME_PATH}${APP_PATH}/bot
      dockerfile: Dockerfile
    container_name: streaming-community-api
    entrypoint: /bin/bash /app/entrypoint.sh
    restart: always
    volumes:
      - ./.env:/app/.env
      - ./config.json:/app/config.json
      - ./entrypoint.sh:/app/entrypoint.sh:ro
      - ${STORAGE_PATH}/jellyfin/media:/app/StreamingCommunity/TelegramHelp/Video/

networks:
  jellyfin_net:
    driver: bridge
