[Interface]
PrivateKey = wIp7TlV5ngvHMZBcJqpU0Izfq5vtBGUIBInmS6C6XVc=
Address = 10.8.0.4/24
#DNS = 1.1.1.1

[Peer]
PublicKey = fOimMwNxkVBnWip3CY0Odx3VWoEMkJG9hyrUWO/RRxQ=
PresharedKey = vEyHQmoyrh2cHSBirhGrWV+ECpmRRqkdo0s5MfCFE+4=
AllowedIPs = 10.8.0.0/24
PersistentKeepalive = 10
Endpoint = wind.giuseppepiccolo.it:51820